

const DummyItems = [
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands u", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors g", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands u", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors g", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands u", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors g", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands u", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors g", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands u", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors g", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands u", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors g", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands u", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors g", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands u", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors g", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands u", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors g", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands u", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors g", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands u", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors g", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands u", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors g", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "Intel 12th and 13th Gen Processors", discount: 43, img: "src/assets/images/g-mouse.png" },
    { id: 1, name: "Men's, Women's, and Kids' Clothing from Amazon Brands", discount: 23, img: "src/assets/images/g-headsets.png" },
    { id: 1, name: "iPhone 12” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/iphone-12.png"},
    { id: 1, name: "ASUS TUF Gaming VG279QM 27” HDR Monitor, 1080P Full HD (1920 x 1080),", discount: 12, img: "src/assets/images/jbl-speaker.png"},
    { id: 1, name: "Honey Can Do Home and Storage Solution Products", discount: 57, img: "src/assets/images/laptops.png" },
    
]

export default DummyItems;